name: Build ML-Example-App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      working-directory: ./ML-Example-App  
      run: chmod +x ./gradlew
    - name: Build with Gradle
      working-directory: ./ML-Example-App  
      run: ./gradlew build
